### Получить задачи на сегодня
GET http://localhost:8085/tasks/filtered?interval=today&completed=true

### Получить задачи на неделю
GET http://localhost:8085/tasks/filtered?interval=week&completed=true

### Получить задачи на месяц
GET http://localhost:8085/tasks/filtered?interval=month&completed=true

### Создать задачу
POST http://localhost:8085/tasks
Content-Type: application/json

{
  "title": "Новая задача",
  "description": "Описание новой задачи",
  "date": "2023-10-11",
  "isCompleted": false
}

### Изменить задачу по идентификатору
PUT http://localhost:8085/tasks/1
Content-Type: application/json

{
  "id": 1,
  "title": "Измененная задача",
  "description": "Описание измененной задачи",
  "date": "2023-10-11",
  "isCompleted": true
}

### Установить/снять метку выполнения задачи
PUT http://localhost:8085/tasks/1/toggle-completion

### Удалить задачу по идентификатору
DELETE http://localhost:8085/tasks/1
