### Получить задачи на сегодня
GET http://localhost:8085/api/v1/tasks/filtered?interval=today&completed=true


### Получить задачи на неделю
GET http://localhost:8085/api/v1/tasks/filtered?interval=week&completed=true

### Получить задачи на месяц
GET http://localhost:8085/api/v1/tasks/filtered?interval=month&completed=true

### Создать задачу
POST http://localhost:8085/api/v1/tasks
Content-Type: application/json

{
  "title": "Новая задача",
  "description": "Описание новой задачи"
}

### Изменить задачу по идентификатору
PATCH http://localhost:8085/api/v1/tasks/1
Content-Type: application/json

{
  "title": "Измененная задача",
  "description": "Описание измененной задачи"
}

### Установить/снять метку выполнения задачи
POST http://localhost:8085/api/v1/tasks/1/toggle-completion


### Удалить задачу по идентификатору
DELETE http://localhost:8085/api/v1/tasks/1
